pluginManagement {
  repositories {
    google {
      content {
        includeGroupByRegex("com\\.android.*")
        includeGroupByRegex("com\\.google.*")
        includeGroupByRegex("androidx.*")
      }
    }
    mavenCentral()
    maven { url "https://jitpack.io" }
    gradlePluginPortal()
  }
}
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
    maven { url 	"https://repo1.maven.org/maven2/"}
    maven { url "https://jitpack.io" }
  }
}

rootProject.name = "Only"
include ':app'
include ':common'
include ':core-preferences'
include ':feature-settings-domain'
include ':navkit'
include ':terminal-emulator'
include ':terminal-view'
include ':baselineprofile'
